exports.seed = async function (knex) {
  await knex('logs').del();

  await knex('logs').insert([
    {
      id: 1,
      municipality_id: 1,
      user_id: 1,
      level: 'INFO',
      module: '/api/auth/login',
      action: 'login',
      message: 'Admin kullanıcısı sisteme giriş yaptı.',
      context: { username: 'admin' },
      ip_address: '10.0.0.5',
      user_agent: 'Mozilla/5.0',
      created_at: knex.fn.now(),
    },
    {
      id: 2,
      municipality_id: 1,
      user_id: 2,
      level: 'WARNING',
      module: '/api/assets/123',
      action: 'update',
      message: 'Varlık güncellemesinde eksik alan uyarısı alındı.',
      context: { asset_id: 123, missing: ['purchase_price'] },
      ip_address: '10.0.0.15',
      user_agent: 'Mozilla/5.0',
      created_at: knex.fn.now(),
    },
    {
      id: 3,
      municipality_id: 2,
      user_id: 3,
      level: 'ERROR',
      module: '/api/asset-movements',
      action: 'create',
      message: 'Taşınır hareketi kaydedilirken veritabanı hatası oluştu.',
      context: { movement_code: 'MOVE-0042', error: 'unique_violation' },
      ip_address: '10.0.0.25',
      user_agent: 'Mozilla/5.0',
      created_at: knex.fn.now(),
    },
    {
      id: 4,
      municipality_id: 3,
      user_id: 4,
      level: 'INFO',
      module: 'superadmin-service',
      action: 'license_check',
      message: 'Yenişehir Belediyesi için lisans son kullanma tarihi doğrulandı.',
      context: { municipality: 'Yenişehir Belediyesi', license_valid: true },
      ip_address: '10.0.0.35',
      user_agent: 'Mozilla/5.0',
      created_at: knex.fn.now(),
    },
    {
      id: 5,
      municipality_id: null,
      user_id: null,
      level: 'CRITICAL',
      module: 'system-health',
      action: 'service_down',
      message: 'Bildirim servisi beklenmedik şekilde durdu. Yeniden başlatma gerekli.',
      context: { service: 'notification-service', restarted: false },
      ip_address: null,
      user_agent: null,
      created_at: knex.fn.now(),
    },
  ]);
};