// 07_assets.js
exports.seed = async function (knex) {
  await knex('assets').del();

  await knex('assets').insert([
    {
      id: 1,
      asset_code: 'ASSET-0001',
      name: 'Dizüstü Bilgisayar',
      description: 'Belediye personeli için laptop',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      assigned_user_id: 4,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.03',
      asset_type: 'demirbas',
      serial_number: 'SN123456',
      purchase_price: 18500,
      purchase_date: '2023-05-10',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 2,
      asset_code: 'ASSET-0002',
      name: 'Ofis Sandalyesi',
      description: 'Ergonomik personel sandalyesi',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 5,
      unit: 'Adet',
      tasinir_code: '253.05.02',
      asset_type: 'demirbas',
      purchase_price: 3500,
      purchase_date: '2022-03-20',
      status: 'active',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 3,
      asset_code: 'ASSET-0003',
      name: 'Masaüstü Bilgisayar',
      description: 'Masaüstü bilgisayar seti (CPU, Monitör, Klavye, Mouse)',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      assigned_user_id: 2,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.01',
      asset_type: 'demirbas',
      serial_number: 'PC-2023-045',
      purchase_price: 12500,
      purchase_date: '2023-08-15',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 4,
      asset_code: 'ASSET-0004',
      name: 'Yazıcı',
      description: 'Lazer yazıcı - A4/A3 baskı desteği',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.05',
      asset_type: 'demirbas',
      serial_number: 'PRT-2023-089',
      purchase_price: 8500,
      purchase_date: '2023-06-20',
      status: 'in_maintenance',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 5,
      asset_code: 'ASSET-0005',
      name: 'Ofis Masası',
      description: 'L şeklinde çalışma masası',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 3,
      unit: 'Adet',
      tasinir_code: '253.05.01',
      asset_type: 'demirbas',
      purchase_price: 4200,
      purchase_date: '2022-11-10',
      status: 'active',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 6,
      asset_code: 'ASSET-0006',
      name: 'Dolap',
      description: 'Dosya dolabı - 4 çekmeceli',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 2,
      unit: 'Adet',
      tasinir_code: '253.05.03',
      asset_type: 'demirbas',
      purchase_price: 2800,
      purchase_date: '2022-09-05',
      status: 'active',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 7,
      asset_code: 'ASSET-0007',
      name: 'Kamyon',
      description: 'Belediye hizmet kamyonu - 3.5 ton',
      category_id: 3,
      department_id: 1,
      location_id: 2,
      assigned_user_id: 4,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.10.01',
      asset_type: 'demirbas',
      serial_number: '34ABC123',
      purchase_price: 450000,
      purchase_date: '2021-04-12',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 8,
      asset_code: 'ASSET-0008',
      name: 'Çöp Toplama Aracı',
      description: 'Kompresörlü çöp toplama aracı',
      category_id: 3,
      department_id: 1,
      location_id: 2,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.10.02',
      asset_type: 'demirbas',
      serial_number: '34XYZ789',
      purchase_price: 850000,
      purchase_date: '2020-08-20',
      status: 'in_maintenance',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 9,
      asset_code: 'ASSET-0009',
      name: 'Traktör',
      description: 'Park ve bahçe işleri için traktör',
      category_id: 3,
      department_id: 2,
      location_id: 3,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.10.03',
      asset_type: 'demirbas',
      serial_number: 'TRK-2020-012',
      purchase_price: 320000,
      purchase_date: '2020-05-15',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 10,
      asset_code: 'ASSET-0010',
      name: 'Çim Biçme Makinesi',
      description: 'Riding çim biçme makinesi',
      category_id: 3,
      department_id: 2,
      location_id: 3,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.10.04',
      asset_type: 'demirbas',
      serial_number: 'CBM-2021-056',
      purchase_price: 125000,
      purchase_date: '2021-07-08',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 11,
      asset_code: 'ASSET-0011',
      name: 'Tablet',
      description: 'Saha çalışmaları için tablet bilgisayar',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      assigned_user_id: 3,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.04',
      asset_type: 'demirbas',
      serial_number: 'TAB-2023-078',
      purchase_price: 6500,
      purchase_date: '2023-09-12',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 12,
      asset_code: 'ASSET-0012',
      name: 'Projeksiyon Cihazı',
      description: 'Toplantı salonu için projeksiyon cihazı',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.06',
      asset_type: 'demirbas',
      serial_number: 'PRJ-2022-034',
      purchase_price: 12000,
      purchase_date: '2022-10-25',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 13,
      asset_code: 'ASSET-0013',
      name: 'Eski Bilgisayar',
      description: 'Hurda durumunda eski masaüstü bilgisayar',
      category_id: 1,
      department_id: 1,
      location_id: 2,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.01',
      asset_type: 'demirbas',
      serial_number: 'OLD-PC-2015',
      purchase_price: 8000,
      purchase_date: '2015-03-10',
      status: 'disposed',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 14,
      asset_code: 'ASSET-0014',
      name: 'Kayıp Sandalye',
      description: 'Kayıp durumunda ofis sandalyesi',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.05.02',
      asset_type: 'demirbas',
      purchase_price: 2500,
      purchase_date: '2021-02-15',
      status: 'lost',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 15,
      asset_code: 'ASSET-0015',
      name: 'Fotokopi Makinesi',
      description: 'Renkli fotokopi ve tarama özellikli',
      category_id: 1,
      department_id: 3,
      location_id: 1,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.03.07',
      asset_type: 'demirbas',
      serial_number: 'FOTO-2022-091',
      purchase_price: 35000,
      purchase_date: '2022-12-05',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 16,
      asset_code: 'ASSET-0016',
      name: 'Toplantı Masası',
      description: '10 kişilik toplantı masası',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.05.04',
      asset_type: 'demirbas',
      purchase_price: 8500,
      purchase_date: '2023-01-18',
      status: 'active',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 17,
      asset_code: 'ASSET-0017',
      name: 'Toplantı Sandalyesi',
      description: 'Toplantı salonu için sandalye seti',
      category_id: 2,
      department_id: 1,
      location_id: 1,
      quantity: 12,
      unit: 'Adet',
      tasinir_code: '253.05.02',
      asset_type: 'demirbas',
      purchase_price: 3200,
      purchase_date: '2023-01-18',
      status: 'active',
      is_qr_tagged: false,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 18,
      asset_code: 'ASSET-0018',
      name: 'Güvenlik Kamerası',
      description: 'IP kamera sistemi - 8 kamera',
      category_id: 1,
      department_id: 1,
      location_id: 1,
      quantity: 8,
      unit: 'Adet',
      tasinir_code: '253.03.08',
      asset_type: 'demirbas',
      purchase_price: 45000,
      purchase_date: '2023-03-22',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 19,
      asset_code: 'ASSET-0019',
      name: 'Su Tankeri',
      description: 'Temizlik ve sulama için su tankeri',
      category_id: 3,
      department_id: 2,
      location_id: 2,
      quantity: 1,
      unit: 'Adet',
      tasinir_code: '253.10.05',
      asset_type: 'demirbas',
      serial_number: '34TNK456',
      purchase_price: 280000,
      purchase_date: '2021-11-30',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
    {
      id: 20,
      asset_code: 'ASSET-0020',
      name: 'Kırıcı Delici',
      description: 'Elektrikli kırıcı delici makine',
      category_id: 3,
      department_id: 1,
      location_id: 3,
      quantity: 2,
      unit: 'Adet',
      tasinir_code: '253.10.06',
      asset_type: 'demirbas',
      purchase_price: 8500,
      purchase_date: '2022-06-14',
      status: 'active',
      is_qr_tagged: true,
      created_by_user_id: 1,
      municipality_id: 1,
    },
  ]);

  await knex.raw(
    "SELECT setval('assets_id_seq', (SELECT MAX(id) FROM assets));"
  );
};
